<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DogPlatform.Genealogy.Application\DogPlatform.Genealogy.Application.csproj" />
    <ProjectReference Include="..\DogPlatform.Genealogy.Infrastructure\DogPlatform.Genealogy.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.Authentication\DogPlatform.Authentication.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.Logging\DogPlatform.Logging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
