<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DogPlatform.Veterinarian.Application\DogPlatform.Veterinarian.Application.csproj" />
    <ProjectReference Include="..\DogPlatform.Veterinarian.Domain\DogPlatform.Veterinarian.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.EventBus\DogPlatform.EventBus.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.Logging\DogPlatform.Logging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
