USE [master];
GO

SET NOCOUNT ON;

IF SUSER_ID(N'IIS APPPOOL\Identity.API') IS NULL
    CREATE LOGIN [IIS APPPOOL\Identity.API] FROM WINDOWS;
IF SUSER_ID(N'IIS APPPOOL\Pets.API') IS NULL
    CREATE LOGIN [IIS APPPOOL\Pets.API] FROM WINDOWS;
IF SUSER_ID(N'IIS APPPOOL\Matching.API') IS NULL
    CREATE LOGIN [IIS APPPOOL\Matching.API] FROM WINDOWS;
IF SUSER_ID(N'IIS APPPOOL\Genealogy.API') IS NULL
    CREATE LOGIN [IIS APPPOOL\Genealogy.API] FROM WINDOWS;
GO

USE [DogPlatform_IdentityDb];
GO

IF USER_ID(N'IIS APPPOOL\Identity.API') IS NULL
    CREATE USER [IIS APPPOOL\Identity.API] FOR LOGIN [IIS APPPOOL\Identity.API];
IF USER_ID(N'IIS APPPOOL\Pets.API') IS NULL
    CREATE USER [IIS APPPOOL\Pets.API] FOR LOGIN [IIS APPPOOL\Pets.API];
IF USER_ID(N'IIS APPPOOL\Matching.API') IS NULL
    CREATE USER [IIS APPPOOL\Matching.API] FOR LOGIN [IIS APPPOOL\Matching.API];
IF USER_ID(N'IIS APPPOOL\Genealogy.API') IS NULL
    CREATE USER [IIS APPPOOL\Genealogy.API] FOR LOGIN [IIS APPPOOL\Genealogy.API];
GO

GRANT INSERT ON OBJECT::[auth].[ErrorLogs] TO [IIS APPPOOL\Identity.API];
GRANT INSERT ON OBJECT::[auth].[ErrorLogs] TO [IIS APPPOOL\Pets.API];
GRANT INSERT ON OBJECT::[auth].[ErrorLogs] TO [IIS APPPOOL\Matching.API];
GRANT INSERT ON OBJECT::[auth].[ErrorLogs] TO [IIS APPPOOL\Genealogy.API];
GO
