<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DogPlatform.Genealogy.Domain\DogPlatform.Genealogy.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.SharedKernel\DogPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.Common\DogPlatform.Common.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
