<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DogPlatform.Pets.Application\DogPlatform.Pets.Application.csproj" />
    <ProjectReference Include="..\DogPlatform.Pets.Domain\DogPlatform.Pets.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.EventBus\DogPlatform.EventBus.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\DogPlatform.Logging\DogPlatform.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.7" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.18" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
